"""Widen extension columns to support longer file extensions

Revision ID: 4ec0c2cae100
Revises: c6a6dd6e43aa
Create Date: 2026-06-18 00:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ec0c2cae100"
down_revision = "c6a6dd6e43aa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("preview_file", schema=None) as batch_op:
        batch_op.alter_column(
            "extension",
            existing_type=sa.String(length=6),
            type_=sa.String(length=10),
            existing_nullable=True,
        )

    with op.batch_alter_table("attachment_file", schema=None) as batch_op:
        batch_op.alter_column(
            "extension",
            existing_type=sa.String(length=6),
            type_=sa.String(length=10),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attachment_file", schema=None) as batch_op:
        batch_op.alter_column(
            "extension",
            existing_type=sa.String(length=10),
            type_=sa.String(length=6),
            existing_nullable=True,
        )

    with op.batch_alter_table("preview_file", schema=None) as batch_op:
        batch_op.alter_column(
            "extension",
            existing_type=sa.String(length=10),
            type_=sa.String(length=6),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
