"""

Revision ID: 81b6486a5229
Revises: d80f02824047
Create Date: 2025-06-25 12:23:47.316732

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = '81b6486a5229'
down_revision = 'd80f02824047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('task_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('person_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timer_person_id'), ['person_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timer_task_id'), ['task_id'], unique=False)

    with op.batch_alter_table('time_spent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_id', sqlalchemy_utils.types.uuid.UUIDType(binary=False), default=uuid.uuid4, nullable=True))
        batch_op.drop_constraint(batch_op.f('time_spent_uc'), type_='unique')
        batch_op.create_unique_constraint('time_spent_uc', ['person_id', 'task_id', 'date', 'timer_id'])
        batch_op.create_index(batch_op.f('ix_time_spent_timer_id'), ['timer_id'], unique=False)
        batch_op.create_foreign_key(None, 'timer', ['timer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_spent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_time_spent_timer_id'))
        batch_op.drop_constraint('time_spent_uc', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('time_spent_uc'), ['person_id', 'task_id', 'date'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('timer_id')

    with op.batch_alter_table('timer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timer_task_id'))
        batch_op.drop_index(batch_op.f('ix_timer_person_id'))

    op.drop_table('timer')
    # ### end Alembic commands ###
